[package]
name = "MusicManager"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.6" 
glib = "0.10"
id3 = "0.6"
chrono = "0.4"
dirs = "5.0"
rusqlite = { version = "0.32.0", features = ["bundled"] }
