[package]
name = "MusicManager"
version = "0.1.0"
edition = "2021"

[dependencies]
id3 = "0.6"
chrono = "0.4"
dirs = "5.0"
rusqlite = { version = "0.32.0", features = ["bundled"] }
gtk = { version = "0.15", features = ["v3_22"] }
glib = "0.15"  
